spring:
  datasource:
    username: admin
    url: jdbc:mysql://database-1.cy6dpdsrdbon.ap-northeast-2.rds.amazonaws.com:3306/perdayonespoon

    password: admin1212
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true



jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: 7OsHFwFI4K218gXQ+GKLzDaeke75U5kbvzOxkXDv8UQ=
      secretKey: t4S4UEmhGiRXWSotB4izFoE6FvdpHohXRW5nJ1we

    s3:

      bucket: springboot-webservice-deploy

